// GENERATED CODE - DO NOT MODIFY BY HAND
// This file was generated by drift_dev

part of 'app_database.dart';

// ignore_for_file: type=lint
// ignore: unnecessary_import

// **************************************************************************
// DatabaseClassGenerator
// **************************************************************************

class $AppDatabase extends AppDatabase {
  $AppDatabase(QueryExecutor e) : super(e);
  
  late final $ProductsTable products = $ProductsTable(this);
  late final $InvoicesTable invoices = $InvoicesTable(this);
  late final $InvoiceItemsTable invoiceItems = $InvoiceItemsTable(this);
  late final $AppSettingsTable appSettings = $AppSettingsTable(this);
  late final $StockMovementsTable stockMovements = $StockMovementsTable(this);
  late final $CategoriesTable categories = $CategoriesTable(this);
  
  @override
  Iterable<TableInfo<Table, Object?>> get allTables => [
    products,
    invoices,
    invoiceItems,
    appSettings,
    stockMovements,
    categories,
  ];
  
  @override
  List<DatabaseSchemaEntity> get allSchemaEntities => [
    ...products.$columns,
    ...invoices.$columns,
    ...invoiceItems.$columns,
    ...appSettings.$columns,
    ...stockMovements.$columns,
    ...categories.$columns,
  ];
}

class $ProductsTable extends Products with TableInfo<Products, Product> {
  @override
  final GeneratedDatabase attachedDatabase;
  
  @override
  final String tableName = 'products';
  
  @override
  final int? schemaVersion;
  
  @override
  List<GeneratedColumn> get columns => [
    id,
    name,
    priceUsd,
    priceLbp,
    barcode,
    category,
    stockQuantity,
    imageUrl,
    description,
    isActive,
    createdAt,
    updatedAt,
  ];
  
  late final GeneratedColumn<int> id = GeneratedColumn<int>(
    'id', aliasedName, false,
    hasAutoIncrement: true,
    type: DriftSqlType.int,
  );
  
  late final GeneratedColumn<String> name = GeneratedColumn<String>(
    'name', aliasedName, false,
    type: DriftSqlType.string,
  );
  
  late final GeneratedColumn<double> priceUsd = GeneratedColumn<double>(
    'price_usd', aliasedName, false,
    type: DriftSqlType.double,
  );
  
  late final GeneratedColumn<double> priceLbp = GeneratedColumn<double>(
    'price_lbp', aliasedName, false,
    type: DriftSqlType.double,
  );
  
  late final GeneratedColumn<String> barcode = GeneratedColumn<String>(
    'barcode', aliasedName, true,
    type: DriftSqlType.string,
  );
  
  late final GeneratedColumn<String> category = GeneratedColumn<String>(
    'category', aliasedName, false,
    type: DriftSqlType.string,
    defaultValue: const Constant('عام'),
  );
  
  late final GeneratedColumn<int> stockQuantity = GeneratedColumn<int>(
    'stock_quantity', aliasedName, false,
    type: DriftSqlType.int,
    defaultValue: const Constant(0),
  );
  
  late final GeneratedColumn<String> imageUrl = GeneratedColumn<String>(
    'image_url', aliasedName, true,
    type: DriftSqlType.string,
  );
  
  late final GeneratedColumn<String> description = GeneratedColumn<String>(
    'description', aliasedName, true,
    type: DriftSqlType.string,
  );
  
  late final GeneratedColumn<bool> isActive = GeneratedColumn<bool>(
    'is_active', aliasedName, false,
    type: DriftSqlType.bool,
    defaultValue: const Constant(true),
  );
  
  late final GeneratedColumn<DateTime> createdAt = GeneratedColumn<DateTime>(
    'created_at', aliasedName, false,
    type: DriftSqlType.dateTime,
    defaultValue: currentDateAndTime,
  );
  
  late final GeneratedColumn<DateTime> updatedAt = GeneratedColumn<DateTime>(
    'updated_at', aliasedName, false,
    type: DriftSqlType.dateTime,
    defaultValue: currentDateAndTime,
  );
  
  $ProductsTable(AttachedDatabase db) : attachedDatabase = db, super(db);
  
  @override
  Row<Product> map(Map<String, dynamic> data, {TablePrefix? tablePrefix}) {
    return Product(
      id: attachedDatabase.typeSystem.read(
        data[tablePrefix?.qualified('id') ?? 'id'],
        DriftSqlType.int,
      ),
      name: attachedDatabase.typeSystem.read(
        data[tablePrefix?.qualified('name') ?? 'name'],
        DriftSqlType.string,
      ),
      priceUsd: attachedDatabase.typeSystem.read(
        data[tablePrefix?.qualified('price_usd') ?? 'price_usd'],
        DriftSqlType.double,
      ),
      priceLbp: attachedDatabase.typeSystem.read(
        data[tablePrefix?.qualified('price_lbp') ?? 'price_lbp'],
        DriftSqlType.double,
      ),
      barcode: attachedDatabase.typeSystem.read(
        data[tablePrefix?.qualified('barcode') ?? 'barcode'],
        DriftSqlType.string,
      ),
      category: attachedDatabase.typeSystem.read(
        data[tablePrefix?.qualified('category') ?? 'category'],
        DriftSqlType.string,
      ),
      stockQuantity: attachedDatabase.typeSystem.read(
        data[tablePrefix?.qualified('stock_quantity') ?? 'stock_quantity'],
        DriftSqlType.int,
      ),
      imageUrl: attachedDatabase.typeSystem.read(
        data[tablePrefix?.qualified('image_url') ?? 'image_url'],
        DriftSqlType.string,
      ),
      description: attachedDatabase.typeSystem.read(
        data[tablePrefix?.qualified('description') ?? 'description'],
        DriftSqlType.string,
      ),
      isActive: attachedDatabase.typeSystem.read(
        data[tablePrefix?.qualified('is_active') ?? 'is_active'],
        DriftSqlType.bool,
      ),
      createdAt: attachedDatabase.typeSystem.read(
        data[tablePrefix?.qualified('created_at') ?? 'created_at'],
        DriftSqlType.dateTime,
      ),
      updatedAt: attachedDatabase.typeSystem.read(
        data[tablePrefix?.qualified('updated_at') ?? 'updated_at'],
        DriftSqlType.dateTime,
      ),
    );
  }
  
  @override
  $ProductsTable get alias => $ProductsTable(attachedDatabase.createAlias(this));
  
  @override
  Expression<int>? get primaryKeyExpression => id;
}

// Similar simplified classes for other tables...
class $InvoicesTable extends Invoices with TableInfo<Invoices, Invoice> {
  @override
  final GeneratedDatabase attachedDatabase;
  @override
  final String tableName = 'invoices';
  @override
  final int? schemaVersion;
  
  @override
  List<GeneratedColumn> get columns => [];
  
  $InvoicesTable(AttachedDatabase db) : attachedDatabase = db, super(db);
  
  @override
  $InvoicesTable get alias => $InvoicesTable(attachedDatabase.createAlias(this));
  
  @override
  Expression<int>? get primaryKeyExpression => null;
}

class $InvoiceItemsTable extends InvoiceItems with TableInfo<InvoiceItem, InvoiceItem> {
  @override
  final GeneratedDatabase attachedDatabase;
  @override
  final String tableName = 'invoice_items';
  @override
  final int? schemaVersion;
  
  @override
  List<GeneratedColumn> get columns => [];
  
  $InvoiceItemsTable(AttachedDatabase db) : attachedDatabase = db, super(db);
  
  @override
  $InvoiceItemsTable get alias => $InvoiceItemsTable(attachedDatabase.createAlias(this));
  
  @override
  Expression<int>? get primaryKeyExpression => null;
}

class $AppSettingsTable extends AppSettings with TableInfo<AppSetting, AppSetting> {
  @override
  final GeneratedDatabase attachedDatabase;
  @override
  final String tableName = 'app_settings';
  @override
  final int? schemaVersion;
  
  @override
  List<GeneratedColumn> get columns => [];
  
  $AppSettingsTable(AttachedDatabase db) : attachedDatabase = db, super(db);
  
  @override
  $AppSettingsTable get alias => $AppSettingsTable(attachedDatabase.createAlias(this));
  
  @override
  Expression<String>? get primaryKeyExpression => null;
}

class $StockMovementsTable extends StockMovements with TableInfo<StockMovement, StockMovement> {
  @override
  final GeneratedDatabase attachedDatabase;
  @override
  final String tableName = 'stock_movements';
  @override
  final int? schemaVersion;
  
  @override
  List<GeneratedColumn> get columns => [];
  
  $StockMovementsTable(AttachedDatabase db) : attachedDatabase = db, super(db);
  
  @override
  $StockMovementsTable get alias => $StockMovementsTable(attachedDatabase.createAlias(this));
  
  @override
  Expression<int>? get primaryKeyExpression => null;
}

class $CategoriesTable extends Categories with TableInfo<Category, Category> {
  @override
  final GeneratedDatabase attachedDatabase;
  @override
  final String tableName = 'categories';
  @override
  final int? schemaVersion;
  
  @override
  List<GeneratedColumn> get columns => [];
  
  $CategoriesTable(AttachedDatabase db) : attachedDatabase = db, super(db);
  
  @override
  $CategoriesTable get alias => $CategoriesTable(attachedDatabase.createAlias(this));
  
  @override
  Expression<int>? get primaryKeyExpression => null;
}
